# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gitipedia 
email: gitipedia@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Gitipedia is a decentralized free encyclopedia built on top of github.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gitipedia.me" # the base hostname & protocol for your site
twitter_username: gitipedia 
github_username: gitipedia 

# Build settings
markdown: kramdown



#languages
l:
  en: English 
  zh: 中文
  
#translate
t:
  en:
    global:
      title: GitiPedia
      description: >
        GitiPedia is a open-source decentralized encyclopedia website built 
        on top of GitHub 
  zh: 
    global:
      title: 基体百科
      description: >
        基体百科是一个建立在GitHub上的开源的去中心化的百科网站,底层是基体里德米（GitiReadMe）